version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/v7"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/v8"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/v9"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/generator"
    schedule:
      interval: "monthly"
