language: go

go:
  - "1.14"
  - "1.15"
  - "1.16"
  - "1.17"
  - "1.18"
  - master

services:
  - docker

before_script:
  - docker pull redislabs/rejson
  - docker run -d -p 6379:6379 --name redis-rejson redislabs/rejson:latest
  - docker ps -a|grep redis-rejson

script:
  - test.sh
