language: go

go:
  - "1.21"
  - "1.22"
  - "1.23"
  - tip

services:
  - docker

before_script:
  - docker pull redislabs/rejson
  - docker run -d -p 6379:6379 --name redis-rejson redislabs/rejson:latest
  - docker ps -a|grep redis-rejson

script:
  - test.sh
