// Code generated by rejonson. DO NOT EDIT.

package rejonson

import "github.com/go-redis/redis"

// ---- JsonGet ----
func JsonGet(processor RedisProcessor, key string, args ...interface{}) *redis.StringCmd {
	paramsToItf := make([]interface{}, 0, 3-1+len(args))
	paramsToItf = append(paramsToItf, "JSON.GET")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, args...)
	cmd := redis.NewStringCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonGet(key string, args ...interface{}) *redis.StringCmd {
	return JsonGet(processor, key, args...)
}
func (processor *Pipeline) JsonGet(key string, args ...interface{}) *redis.StringCmd {
	return JsonGet(processor, key, args...)
}

// ---- JsonDel ----
func JsonDel(processor RedisProcessor, key string, args ...interface{}) *redis.IntCmd {
	paramsToItf := make([]interface{}, 0, 3-1+len(args))
	paramsToItf = append(paramsToItf, "JSON.DEL")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, args...)
	cmd := redis.NewIntCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonDel(key string, args ...interface{}) *redis.IntCmd {
	return JsonDel(processor, key, args...)
}
func (processor *Pipeline) JsonDel(key string, args ...interface{}) *redis.IntCmd {
	return JsonDel(processor, key, args...)
}

// ---- JsonSet ----
func JsonSet(processor RedisProcessor, key string, path string, json string, args ...interface{}) *redis.StatusCmd {
	paramsToItf := make([]interface{}, 0, 5-1+len(args))
	paramsToItf = append(paramsToItf, "JSON.SET")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, path)
	paramsToItf = append(paramsToItf, json)
	paramsToItf = append(paramsToItf, args...)
	cmd := redis.NewStatusCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonSet(key string, path string, json string, args ...interface{}) *redis.StatusCmd {
	return JsonSet(processor, key, path, json, args...)
}
func (processor *Pipeline) JsonSet(key string, path string, json string, args ...interface{}) *redis.StatusCmd {
	return JsonSet(processor, key, path, json, args...)
}

// ---- JsonMGet ----
func JsonMGet(processor RedisProcessor, key string, args ...interface{}) *redis.StringSliceCmd {
	paramsToItf := make([]interface{}, 0, 3-1+len(args))
	paramsToItf = append(paramsToItf, "JSON.MGET")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, args...)
	cmd := redis.NewStringSliceCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonMGet(key string, args ...interface{}) *redis.StringSliceCmd {
	return JsonMGet(processor, key, args...)
}
func (processor *Pipeline) JsonMGet(key string, args ...interface{}) *redis.StringSliceCmd {
	return JsonMGet(processor, key, args...)
}

// ---- JsonType ----
func JsonType(processor RedisProcessor, key string, path string) *redis.StringCmd {
	paramsToItf := make([]interface{}, 0, 3)
	paramsToItf = append(paramsToItf, "JSON.TYPE")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, path)
	cmd := redis.NewStringCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonType(key string, path string) *redis.StringCmd {
	return JsonType(processor, key, path)
}
func (processor *Pipeline) JsonType(key string, path string) *redis.StringCmd {
	return JsonType(processor, key, path)
}

// ---- JsonNumIncrBy ----
func JsonNumIncrBy(processor RedisProcessor, key string, path string, value int) *redis.StringCmd {
	paramsToItf := make([]interface{}, 0, 4)
	paramsToItf = append(paramsToItf, "JSON.NUMINCRBY")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, path)
	paramsToItf = append(paramsToItf, value)
	cmd := redis.NewStringCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonNumIncrBy(key string, path string, value int) *redis.StringCmd {
	return JsonNumIncrBy(processor, key, path, value)
}
func (processor *Pipeline) JsonNumIncrBy(key string, path string, value int) *redis.StringCmd {
	return JsonNumIncrBy(processor, key, path, value)
}

// ---- JsonNumMultBy ----
func JsonNumMultBy(processor RedisProcessor, key string, path string, value int) *redis.StringCmd {
	paramsToItf := make([]interface{}, 0, 4)
	paramsToItf = append(paramsToItf, "JSON.NUMMULTBY")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, path)
	paramsToItf = append(paramsToItf, value)
	cmd := redis.NewStringCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonNumMultBy(key string, path string, value int) *redis.StringCmd {
	return JsonNumMultBy(processor, key, path, value)
}
func (processor *Pipeline) JsonNumMultBy(key string, path string, value int) *redis.StringCmd {
	return JsonNumMultBy(processor, key, path, value)
}

// ---- JsonStrAppend ----
func JsonStrAppend(processor RedisProcessor, key string, path string, value string) *redis.IntCmd {
	paramsToItf := make([]interface{}, 0, 4)
	paramsToItf = append(paramsToItf, "JSON.STRAPPEND")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, path)
	paramsToItf = append(paramsToItf, value)
	cmd := redis.NewIntCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonStrAppend(key string, path string, value string) *redis.IntCmd {
	return JsonStrAppend(processor, key, path, value)
}
func (processor *Pipeline) JsonStrAppend(key string, path string, value string) *redis.IntCmd {
	return JsonStrAppend(processor, key, path, value)
}

// ---- JsonStrLen ----
func JsonStrLen(processor RedisProcessor, key string, path string) *redis.IntCmd {
	paramsToItf := make([]interface{}, 0, 3)
	paramsToItf = append(paramsToItf, "JSON.STRLEN")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, path)
	cmd := redis.NewIntCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonStrLen(key string, path string) *redis.IntCmd {
	return JsonStrLen(processor, key, path)
}
func (processor *Pipeline) JsonStrLen(key string, path string) *redis.IntCmd {
	return JsonStrLen(processor, key, path)
}

// ---- JsonArrAppend ----
func JsonArrAppend(processor RedisProcessor, key string, path string, args ...interface{}) *redis.IntCmd {
	paramsToItf := make([]interface{}, 0, 4-1+len(args))
	paramsToItf = append(paramsToItf, "JSON.ARRAPPEND")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, path)
	paramsToItf = append(paramsToItf, args...)
	cmd := redis.NewIntCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonArrAppend(key string, path string, args ...interface{}) *redis.IntCmd {
	return JsonArrAppend(processor, key, path, args...)
}
func (processor *Pipeline) JsonArrAppend(key string, path string, args ...interface{}) *redis.IntCmd {
	return JsonArrAppend(processor, key, path, args...)
}

// ---- JsonArrIndex ----
func JsonArrIndex(processor RedisProcessor, key string, path string, value interface{}, startAndStop ...interface{}) *redis.IntCmd {
	paramsToItf := make([]interface{}, 0, 5-1+len(startAndStop))
	paramsToItf = append(paramsToItf, "JSON.ARRINDEX")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, path)
	paramsToItf = append(paramsToItf, value)
	paramsToItf = append(paramsToItf, startAndStop...)
	cmd := redis.NewIntCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonArrIndex(key string, path string, value interface{}, startAndStop ...interface{}) *redis.IntCmd {
	return JsonArrIndex(processor, key, path, value, startAndStop...)
}
func (processor *Pipeline) JsonArrIndex(key string, path string, value interface{}, startAndStop ...interface{}) *redis.IntCmd {
	return JsonArrIndex(processor, key, path, value, startAndStop...)
}

// ---- JsonArrInsert ----
func JsonArrInsert(processor RedisProcessor, key string, path string, index int, values ...interface{}) *redis.IntCmd {
	paramsToItf := make([]interface{}, 0, 5-1+len(values))
	paramsToItf = append(paramsToItf, "JSON.ARRINSERT")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, path)
	paramsToItf = append(paramsToItf, index)
	paramsToItf = append(paramsToItf, values...)
	cmd := redis.NewIntCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonArrInsert(key string, path string, index int, values ...interface{}) *redis.IntCmd {
	return JsonArrInsert(processor, key, path, index, values...)
}
func (processor *Pipeline) JsonArrInsert(key string, path string, index int, values ...interface{}) *redis.IntCmd {
	return JsonArrInsert(processor, key, path, index, values...)
}

// ---- JsonArrLen ----
func JsonArrLen(processor RedisProcessor, key string, path string) *redis.IntCmd {
	paramsToItf := make([]interface{}, 0, 3)
	paramsToItf = append(paramsToItf, "JSON.ARRLEN")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, path)
	cmd := redis.NewIntCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonArrLen(key string, path string) *redis.IntCmd {
	return JsonArrLen(processor, key, path)
}
func (processor *Pipeline) JsonArrLen(key string, path string) *redis.IntCmd {
	return JsonArrLen(processor, key, path)
}

// ---- JsonArrPop ----
func JsonArrPop(processor RedisProcessor, key string, path string, index int) *redis.StringCmd {
	paramsToItf := make([]interface{}, 0, 4)
	paramsToItf = append(paramsToItf, "JSON.ARRPOP")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, path)
	paramsToItf = append(paramsToItf, index)
	cmd := redis.NewStringCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonArrPop(key string, path string, index int) *redis.StringCmd {
	return JsonArrPop(processor, key, path, index)
}
func (processor *Pipeline) JsonArrPop(key string, path string, index int) *redis.StringCmd {
	return JsonArrPop(processor, key, path, index)
}

// ---- JsonArrTrim ----
func JsonArrTrim(processor RedisProcessor, key string, path string, start int, stop int) *redis.IntCmd {
	paramsToItf := make([]interface{}, 0, 5)
	paramsToItf = append(paramsToItf, "JSON.ARRTRIM")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, path)
	paramsToItf = append(paramsToItf, start)
	paramsToItf = append(paramsToItf, stop)
	cmd := redis.NewIntCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonArrTrim(key string, path string, start int, stop int) *redis.IntCmd {
	return JsonArrTrim(processor, key, path, start, stop)
}
func (processor *Pipeline) JsonArrTrim(key string, path string, start int, stop int) *redis.IntCmd {
	return JsonArrTrim(processor, key, path, start, stop)
}

// ---- JsonObjKeys ----
func JsonObjKeys(processor RedisProcessor, key string, path string) *redis.StringSliceCmd {
	paramsToItf := make([]interface{}, 0, 3)
	paramsToItf = append(paramsToItf, "JSON.OBJKEYS")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, path)
	cmd := redis.NewStringSliceCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonObjKeys(key string, path string) *redis.StringSliceCmd {
	return JsonObjKeys(processor, key, path)
}
func (processor *Pipeline) JsonObjKeys(key string, path string) *redis.StringSliceCmd {
	return JsonObjKeys(processor, key, path)
}

// ---- JsonObjLen ----
func JsonObjLen(processor RedisProcessor, key string, path string) *redis.IntCmd {
	paramsToItf := make([]interface{}, 0, 3)
	paramsToItf = append(paramsToItf, "JSON.OBJLEN")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, path)
	cmd := redis.NewIntCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonObjLen(key string, path string) *redis.IntCmd {
	return JsonObjLen(processor, key, path)
}
func (processor *Pipeline) JsonObjLen(key string, path string) *redis.IntCmd {
	return JsonObjLen(processor, key, path)
}

// ---- JsonClear ----
func JsonClear(processor RedisProcessor, key string, path string) *redis.IntCmd {
	paramsToItf := make([]interface{}, 0, 3)
	paramsToItf = append(paramsToItf, "JSON.CLEAR")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, path)
	cmd := redis.NewIntCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonClear(key string, path string) *redis.IntCmd {
	return JsonClear(processor, key, path)
}
func (processor *Pipeline) JsonClear(key string, path string) *redis.IntCmd {
	return JsonClear(processor, key, path)
}

// ---- JsonForget ----
func JsonForget(processor RedisProcessor, key string, path string) *redis.IntCmd {
	paramsToItf := make([]interface{}, 0, 3)
	paramsToItf = append(paramsToItf, "JSON.FORGET")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, path)
	cmd := redis.NewIntCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonForget(key string, path string) *redis.IntCmd {
	return JsonForget(processor, key, path)
}
func (processor *Pipeline) JsonForget(key string, path string) *redis.IntCmd {
	return JsonForget(processor, key, path)
}

// ---- JsonMerge ----
func JsonMerge(processor RedisProcessor, key string, path string, value string) *redis.StatusCmd {
	paramsToItf := make([]interface{}, 0, 4)
	paramsToItf = append(paramsToItf, "JSON.MERGE")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, path)
	paramsToItf = append(paramsToItf, value)
	cmd := redis.NewStatusCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonMerge(key string, path string, value string) *redis.StatusCmd {
	return JsonMerge(processor, key, path, value)
}
func (processor *Pipeline) JsonMerge(key string, path string, value string) *redis.StatusCmd {
	return JsonMerge(processor, key, path, value)
}

// ---- JsonMSet ----
func JsonMSet(processor RedisProcessor, args ...interface{}) *redis.StatusCmd {
	paramsToItf := make([]interface{}, 0, 2-1+len(args))
	paramsToItf = append(paramsToItf, "JSON.MSET")
	paramsToItf = append(paramsToItf, args...)
	cmd := redis.NewStatusCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonMSet(args ...interface{}) *redis.StatusCmd {
	return JsonMSet(processor, args...)
}
func (processor *Pipeline) JsonMSet(args ...interface{}) *redis.StatusCmd {
	return JsonMSet(processor, args...)
}

// ---- JsonSetMode ----
func JsonSetMode(processor RedisProcessor, key string, path string, value string, mode string) *redis.StatusCmd {
	paramsToItf := make([]interface{}, 0, 5)
	paramsToItf = append(paramsToItf, "JSON.SET")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, path)
	paramsToItf = append(paramsToItf, value)
	paramsToItf = append(paramsToItf, mode)
	cmd := redis.NewStatusCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonSetMode(key string, path string, value string, mode string) *redis.StatusCmd {
	return JsonSetMode(processor, key, path, value, mode)
}
func (processor *Pipeline) JsonSetMode(key string, path string, value string, mode string) *redis.StatusCmd {
	return JsonSetMode(processor, key, path, value, mode)
}

// ---- JsonToggle ----
func JsonToggle(processor RedisProcessor, key string, path string) *redis.IntCmd {
	paramsToItf := make([]interface{}, 0, 3)
	paramsToItf = append(paramsToItf, "JSON.TOGGLE")
	paramsToItf = append(paramsToItf, key)
	paramsToItf = append(paramsToItf, path)
	cmd := redis.NewIntCmd(paramsToItf...)
	// ignore returned error, it is part of the cmd
	_ = processor.Process(cmd)
	return cmd
}
func (processor *Client) JsonToggle(key string, path string) *redis.IntCmd {
	return JsonToggle(processor, key, path)
}
func (processor *Pipeline) JsonToggle(key string, path string) *redis.IntCmd {
	return JsonToggle(processor, key, path)
}

// RedisProcessor is redis client or pipeline instance that will process a command
type RedisProcessor interface {
	Process(redis.Cmder) error
}

/*
Client is an extended redis.Client, stores a pointer to the original redis.Client
*/
type Client struct {
	*redis.Client
}

/*
Pipeline is an extended redis.Pipeline, stores a pointer to the original redis.Pipeliner
*/
type Pipeline struct {
	redis.Pipeliner
}

func (cl *Client) Pipeline() *Pipeline {
	pip := cl.Client.Pipeline()
	return ExtendPipeline(pip)
}

func (cl *Client) TXPipeline() *Pipeline {
	pip := cl.Client.TxPipeline()
	return ExtendPipeline(pip)
}
func (pl *Pipeline) Pipeline() *Pipeline {
	pip := pl.Pipeliner.Pipeline()
	return ExtendPipeline(pip)
}

func ExtendClient(client *redis.Client) *Client {
	return &Client{
		client,
	}
}

func ExtendPipeline(pipeline redis.Pipeliner) *Pipeline {
	return &Pipeline{
		pipeline,
	}
}
