blank_issues_enabled: false
contact_links:
  - name: Security Issue
    url: https://github.com/KromDaniel/rejonson/security/policy
    about: Please review our security policy for reporting vulnerabilities.
